INSERT INTO `tblPerson` (`ID`, `FirstName`, `MiddleName`, `LastName`, `FamilyID`, `ChurchID`, `Status`, `xBirthDate`, `Baptized`, `xBaptizedDate`, `Confirmed`, `xConfirmedDate`, `Member`, `xMemberDate`, `AssociateMember`, `xAssociateMemberDate`, `Note`, `Picture`, `xInsuranceVerified`, `xEmergencyContact`, `xEmergencyContactPhone`) VALUES
(1, 'David', '', 'Berglund', 1, 1, 'Non Member', '1958-03-06 00:00:00', True, 'None', True, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(2, 'Heidi', '', 'Berglund', 1, 1, 'Active', '1963-08-10 00:00:00', True, '1963-08-25 00:00:00', True, '1977-05-01 00:00:00', True, 'None', False, 'None', '', '', False, '', ''),
(3, 'Spencer', '', 'Berglund', 1, 1, 'Active', '2005-07-21 00:00:00', True, '2005-07-21 00:00:00', True, '2018-10-21 00:00:00', True, 'None', False, 'None', '', '', False, '', ''),
(4, 'Kendra', 'Lee', 'Berglund', 1, 1, 'Active', '2007-06-20 00:00:00', True, '2007-07-01 00:00:00', False, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(5, 'Rachel', '', 'Berglund', 2, 1, 'Active', 'None', True, 'None', True, 'None', True, 'None', False, 'None', '', 'Berglund.Rachel.jpg', False, '', ''),
(6, 'Daniel', '', 'Berglund', 2, 1, 'Active', 'None', True, 'None', True, 'None', True, 'None', False, 'None', '', 'Berglund.Danny.jpg', False, '', ''),
(7, 'Julia', '', 'Berglund', 2, 1, 'Active', 'None', True, 'None', True, '2018-10-21 00:00:00', True, 'None', False, 'None', '', 'Berglund.Julia.jpg', False, '', ''),
(8, 'Russell', 'Wayne', 'Berglund', 2, 1, 'Active', '2007-09-19 00:00:00', True, 'None', False, 'None', True, 'None', False, 'None', '', 'Berglund.Russell.jpg', False, '', ''),
(9, 'John', '', 'Bockovich', 3, 1, 'Inactive', 'None', False, 'None', False, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(10, 'Sandra', '', 'Bockovich', 3, 1, 'Inactive', 'None', False, 'None', False, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(11, 'Hallie', '', 'Bockovich', 3, 1, 'Inactive', 'None', False, 'None', False, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(12, 'Daniel', '', 'Bockovich', 3, 1, 'Inactive', 'None', False, 'None', False, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(13, 'Greg', '', 'Gecas', 4, 1, 'Active', 'None', True, 'None', True, 'None', True, 'None', False, 'None', '', 'Greg Gecas.jpg', False, '', ''),
(14, 'Barb', '', 'Gecas', 4, 1, 'Active', 'None', True, 'None', True, 'None', True, 'None', False, 'None', '', 'Barb Gecas.jpg', False, '', ''),
(15, 'Robert', '', 'Gecas', 4, 1, 'Inactive', 'None', True, 'None', True, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(16, 'Paul', '', 'Gecas', 19, 1, 'Active', 'None', True, 'None', True, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(17, 'Addie', '', 'Gecas', 4, 1, 'Inactive', 'None', True, 'None', True, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(18, 'Jason', '', 'Mesenbring', 5, 1, 'Active', 'None', True, 'None', True, 'None', True, 'None', False, 'None', '', 'Mesenbring, Jay.jpg', False, '', ''),
(19, 'Lisa', '', 'Mesenbring', 5, 1, 'Active', 'None', True, 'None', True, 'None', True, 'None', False, 'None', '', 'Mesenbring, Lisa.jpg', False, '', ''),
(20, 'Robert', 'Theodore', 'Mesenbring', 6, 1, 'Active', 'None', True, '1936-08-23 00:00:00', True, '1950-04-02 00:00:00', True, '2000-01-01 00:00:00', False, 'None', '', 'Mesenbring.Bob.jpg', False, '', ''),
(21, 'Georgianna', 'Luella', 'Mesenbring', 6, 1, 'Active', 'None', True, '1940-11-17 00:00:00', True, '1954-04-15 00:00:00', True, '2000-01-01 00:00:00', False, 'None', '', 'Mesenbring.Jan.jpg', False, '', ''),
(22, 'Jason', '', 'Lashinski', 7, 1, 'Inactive', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(23, 'Sherrie', '', 'Pauling', 7, 1, 'Inactive', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(24, 'Devan', '', 'Pauling', 7, 1, 'Inactive', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(25, 'Paul', '', 'Higgins', 8, 1, 'Inactive', 'None', True, 'None', True, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(26, 'Carolyn', '', 'Higgins', 8, 1, 'Non Member', 'None', True, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(27, 'Mike', '', 'Raymond', 9, 1, 'Active', 'None', True, 'None', True, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(28, 'Bob', '', 'Ulmer', 10, 2, 'Associate', 'None', True, 'None', True, 'None', False, 'None', True, 'None', '', '', False, '', ''),
(29, 'Martha', '', 'Ulmer', 10, 2, 'Associate', 'None', True, 'None', True, 'None', False, 'None', True, 'None', '', '', False, '', ''),
(30, 'Jonathan', 'Charles', 'Watt', 11, 1, 'Active', '1961-12-28 00:00:00', True, 'None', True, 'None', True, '2019-08-01 00:00:00', False, 'None', '', '', False, '', ''),
(31, 'Hannah', 'Kristine Maraie', 'Watt', 11, 1, 'At School', '1998-06-10 00:00:00', True, 'None', True, 'None', True, '2019-07-10 00:00:00', False, 'None', '', '', False, '', ''),
(33, 'Daniel', '', 'Damschen', 14, 1, 'Deceased', 'None', True, 'None', True, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(34, 'Janice', '', 'Damschen', 14, 1, 'Non Member', 'None', True, 'None', True, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(41, 'Erik', 'David', 'Saunders', 18, 1, 'Active', '1987-02-01 00:00:00', True, '1987-02-15 00:00:00', True, '2000-05-21 00:00:00', True, '2019-07-10 00:00:00', False, 'None', '', 'Saunders, E.jpg', False, '', ''),
(42, 'Katherine', 'Lynn', 'Saunders', 18, 1, 'Active', '1989-05-04 00:00:00', True, '1989-05-14 00:00:00', True, '2004-05-02 00:00:00', True, '2019-07-10 00:00:00', False, 'None', '', 'Saunders,k.jpg', False, '', ''),
(55, 'David', '', 'Gesch', 69, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(56, 'Heidi', '', 'Gesch', 69, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(58, 'Ed', '', 'Lisuth', 70, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(59, 'Mary', '', 'Lisuth', 70, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(61, 'Ruth', '', 'Saunders', 71, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(62, 'Rolf', '', 'Preus', 72, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(63, 'Steve', '', 'Saunders', 71, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(64, 'Thomas', '', 'Saunders', 71, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(65, 'Daniel', '', 'Preus', 73, 0, 'Visitor', 'None', False, 'None', False, 'None', True, '2021-10-20 00:00:00', False, 'None', '', '', False, '', ''),
(66, 'Linda', '', 'Prues', 73, 0, 'Visitor', 'None', False, 'None', False, 'None', True, '2021-10-20 00:00:00', False, 'None', '', '', False, '', ''),
(69, 'Dan', '', 'Benolkin', 75, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(70, 'Heidi', '', 'Benolkin', 75, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(71, 'Randy', '', 'Nemiz', 76, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(72, 'Dana', '', 'Nimiz', 76, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(73, 'Jodi', '', 'Kolhiff', 77, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(75, 'Merlin', '', 'Higgins', 78, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(76, 'Gerald (Jerry)', '', 'Anderson', 79, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(77, 'Mike', '', 'Flack', 80, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(78, 'Carol', '', 'Flack', 80, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(79, 'Geri', '', 'Heston', 81, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '<div>Greg\'s Sister</div>



<div>Not connected to any church</div>', '', False, '', ''),
(80, 'Jim', '', 'LeTourneau', 82, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(81, 'Sharlene', '', 'LeTourneu', 82, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(82, 'Jason', '', 'Lushinski', 83, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(83, 'Sherri', '', 'Lushinski', 83, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(84, 'Mark', '', 'Penning', 84, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(85, 'Cathy', '', 'Penning', 84, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(86, 'Linda', '', 'Wizykoski', 85, 0, 'Prospect', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(107, 'Luke', '', 'Preus', 86, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(108, 'Rachel', '', 'Prues', 86, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(109, 'Christian', '', 'Preus', 87, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(110, 'Cindy', '', 'Preus', 87, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(111, 'Janet', '', 'Preus', 88, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(112, 'Bill', '', 'Schmidt', 89, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(113, 'Kim', '', 'Schmidt', 89, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(114, 'Charlie', '', 'Schmidt', 89, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(115, 'Jack', '', 'Schmidt', 89, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(116, 'Rochelle', '', 'Faley', 90, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(117, 'Karren', '', 'Perkins', 91, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(118, 'Jude', '', 'Perkins', 91, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(120, 'Madiline', '', 'Perkins', 91, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(121, 'Seth', '', 'Prues', 92, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(122, 'William', '', 'Sabol', 93, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(123, 'Natalie', '', 'Sabol', 93, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(124, 'Ryan', '', 'Sabol', 93, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(125, 'Kristof', '', 'Sabol', 93, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(126, 'Miciah', '', 'Carter', 94, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(127, 'Everett', '', 'Carter', 94, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(128, 'Fritz', '', 'Carter', 94, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(129, 'Brian', '', 'Nemanic', 95, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(130, 'Deborah', '', 'Nemanic', 95, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(131, 'Zachariah', '', 'Watt', 96, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(132, 'Nathaniel', '', 'Watt', 97, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(133, 'Teri', '', 'Watt', 97, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(135, 'Julie', '', 'Preus', 98, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(136, 'Pete', '', 'Prues', 98, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(137, 'Cindy', '', 'Prues', 99, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(138, 'Christian', '', 'Prues', 87, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(139, 'Kristiana', '', 'Prues', 100, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(140, 'Jody', '', 'Preus', 101, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(141, 'Erik', '', 'Preus', 101, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(142, 'Michael', '', 'Perkins', 91, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(143, 'Pete', '', 'Hofius', 104, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(145, 'Pat', '', 'Kerber', 105, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(146, 'Steve', '', 'Larson', 107, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(147, 'Lawrence', '', 'Bottorff', 108, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(148, 'Roger', '', 'Micen', 109, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(149, 'Rochelle', '', 'Staley', 110, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(150, 'Matthew', '', 'Johnson', 111, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(151, 'Leah', '', 'Johnson', 111, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(152, 'Josef', '', 'Johnson', 111, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(153, 'Elizabeth', '', 'Bergland', 113, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(154, 'Daniel', '', 'Unknown', 114, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(155, 'Christiana', '', 'Unknown', 114, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(156, 'Elizabeth', '', 'Unknown', 114, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(157, 'William', '', 'Unknown', 114, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(158, 'Brooke', '', 'Unknown', 114, 0, 'Visitor', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(159, 'Test', 'Test', 'Test', 115, 0, 'Volunteer', 'None', True, 'None', True, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(161, 'test', 'test', 'test', 115, 0, 'Volunteer', 'None', False, 'None', False, 'None', False, 'None', False, 'None', '', '', False, '', ''),
(162, 'Axel', '', 'Zimmer', 116, '', 'Active', 'None', True, '2021-10-24 00:00:00', False, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(164, 'Lori', '', 'Stangler', 118, '', 'Active', '1958-03-04 00:00:00', False, 'None', False, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(165, 'Randy', '', 'Stangler', 118, '', 'Active', 'None', False, 'None', False, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(166, 'Janet', '', 'Rinquist', 119, '', 'Active', '1950-08-25 00:00:00', False, 'None', False, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(167, 'James', '', 'Rinquist', 119, '', 'Active', '1945-05-26 00:00:00', False, 'None', False, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(168, 'Paul', '', 'Muus', 120, '', 'Active', 'None', False, 'None', False, 'None', True, 'None', False, 'None', '', '', False, '', ''),
(169, 'Bonnie', '', 'Muus', 120, '', 'Active', 'None', False, 'None', False, 'None', True, 'None', False, 'None', '', '', False, '', '');